# Change these first
owner: revinet-status # Your GitHub organization or username, where this repository lives
repo: k-fediverse-status # The name of this repository

# following check must be present:
# __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
# TODO: ABC order
# name에 한글 입력 안 됩니다. 라틴알파벳 타파해야... (아무말)

sites:
  - name: planet.moe
    url: https://planet.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: amaurot.city
    url: https://amaurot.city/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Aniwork Network
    url: https://ani.work/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: ChalkBoard
    url: https://chalk.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Dimension
    url: https://dimension.host/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: naru.cafe DON
    url: https://don.naru.cafe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: HotoMoe
    url: https://hoto.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 0
      - 404
  - name: Misskey.lapy
    url: https://k.lapy.link/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: madost.one
    url: https://madost.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: masost.one
    url: https://masost.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: mustard.blog
    url: https://mustard.blog/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: qdon.space
    url: https://qdon.space/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Old Sharlayan
    url: https://old.sharlayan.city/nodeinfo/2.0
    assignees:
      - revi
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: SiFNet
    url: https://social.silicon.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: YuruToot
    url: https://toot.funami.tech/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: uri.life
    url: https://uri.life/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: yoyang.one
    url: https://yoyang.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Bunbers
    url: https://bunbers.org/nodeinfo/2.0.json
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: jmm
    url: https://jmm.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: maratang.life
    url: https://maratang.life/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: kurry.social
    url: https://kurry.social/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: pointless.chat
    url: https://pointless.chat/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: muri.network
    url: https://muri.network/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: netsphere.one
    url: https://netsphere.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: mnetwork.co.kr
    url: https://mastodon.mnetwork.co.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: t.chadole.com
    url: https://t.chadole.com/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: krpgpub.net
    url: https://krpgpub.net/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: bakedbean.xyz
    url: https://bakedbean.xyz/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: kono.pub
    url: https://kono.pub/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: trpg-o.xyz
    url: https://trpg-o.xyz/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: s.mysw.moe
    url: https://s.mysw.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: buttersc.one
    url: https://buttersc.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: stella.place
    url: https://stella.place/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: iqhina.org
    url: https://iqhina.org/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: sharlayan.in
    url: https://sharlayan.in/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Cerulean.ink
    url: https://cerulean.ink/nodeinfo/2.0.json
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: KitsuneSoba
    url: https://kitsunesoba.com/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Catsword.social
    url: https://catswords.social/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: duk.space
    url: https://duk.space/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: mst.canor.kr
    url: https://mst.canor.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: msk.canor.kr
    url: https://msk.canor.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: serafuku.moe
    url: https://serafuku.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Yodangang.Express
    url: https://yodangang.express/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Nekoplanet
    url: https://nekoplanet.xyz/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: worldcone
    url: https://worldc.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: i.peacht.art
    url: https://i.peacht.art/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: rlidea.com
    url: https://rlidea.com/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: leuno.kr
    url: https://leuno.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: mi.rerac.dev
    url: https://mi.rerac.dev/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: parfait.day
    url: https://parfait.day/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: whitelily.blue
    url: https://whitelily.blue/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: sekai.social
    url: https://sekai.social/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: yuri.garden
    url: https://yuri.garden/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: aquarium.yuri.garden
    url: https://aquarium.yuri.garden/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: yunochi.moe
    url: https://yunochi.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: munochi.moe
    url: https://munochi.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: FediverseWiki
    url: https://wiki.mastodon.kr/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=json
  - name: interstellar.flights
    url: https://ap.interstellar.flights/
  - name: relay.musubi.moe
    url: https://relay.musubi.moe/
  - name: relay.pointless.chat
    url: https://relay.pointless.chat/
# FediverseWiki와 그 아래 사이트의 순서는 만지지 말아 주세요.

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fediverse.kr
  # baseUrl: /your-repo-name
  logoUrl: https://static.miraheze.org/mastodonkrwiki/b/b4/%EB%A7%88.svg
  name: K-연합우주 상태창
  introTitle: "K-연합우주 상태창"
  introMessage: "[Upptime](https://github.com/upptime/upptime)으로 보는 K-연합우주 서버상태창. 자세한 정보는 [한국어 연합우주 위키](https://wiki.mastodon.kr/wiki/Status.fediverse.kr)을 참조해 주세요."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  customHeadHtml: "<meta name=\"robots\" content=\"noindex\">"

commitMessages:
  commitAuthorName: "revibot"
  commitAuthorEmail: "github-revibot@revi.kr"

workflowSchedule:
  graphs: "0 3,9,15,21 * * *"
  responseTime: "0 */6 * * *"
  staticSite: "0 17 * * *"
  summary: "59 */6 * * *"
  updateTemplate: "0 15 * * 1"
  updates: "0 20 * * *"
  uptime: "*/5 * * * *"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

user-agent: upptime(@revinet-status, v2023-09-09)/ contact https://github.com/revi for issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
